###
GET http://localhost:3000/post

###

GET http://localhost:3000/post?sender=123456

###
GET http://localhost:3000/post/6362c7636d199ef17e835cfd
###
GET http://localhost:3000/message
###
post http://localhost:3000/message
###
post http://localhost:3000/post
Content-Type: application/json

{
    "message":"this is my new message ",
    "sender":"123456"

}
###
PUT http://localhost:3000/post/63791f38cbd2beb3c1db8441
Content-Type: application/json

{
    "message":"this is Update",
    "sender":"123456"

}